tunnel: ${CF_TUNNEL_ID}
credentials-file: /etc/cloudflared/${CF_TUNNEL_ID}.json
ingress:
  - hostname: traefik.${DOMAIN}
    service: http://traefik:80
  - hostname: jellyfin.${DOMAIN}
    service: http://jellyfin:8096
  - hostname: qb.${DOMAIN}
    service: http://qbittorrent:8080
  - hostname: kuma.${DOMAIN}
    service: http://uptime-kuma:3001
  - hostname: webui.${DOMAIN}
    service: http://openwebui:8080
  - hostname: pihole.${DOMAIN}
    service: http://pihole:80
  - hostname: git.${DOMAIN}
    service: http://forgejo:3000
  - hostname: marist.dev
    service: http://traefik:80
  - service: http_status:404
